server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:5174
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**,/api/admin/users/**,/api/admin/categories/**,/api/auth/login,/api/auth/register,/api/auth/send-otp,/api/auth/verify-otp,/oauth2/**,/login/oauth2/**,/api/internal/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/hello

        - id: tts-service
          uri: lb://tts-service
          predicates:
            - Path=/api/tts/convert,/api/tts/save,/api/tts/upload,/api/tts/audios/**,/api/tts/health

        - id: test-service
#          uri: http://localhost:8087
          uri: http://localhost:8088

          predicates:
            - Path=/api/tests/**

        - id: speech-recognition-service
          uri: lb://speech-recognition-service
          predicates:
            - Path=/api/pronunciation/**

        - id: classroom-service
          uri: lb://classroom-service
          predicates:
            - Path=/api/classrooms/**,/api/admin/classrooms/**,/api/student/classrooms/**,/api/student/invitations/**,/api/internal/classrooms/**,/api/internal/invitations/**

        - id: lesson-service
          uri: lb://lesson-service
          predicates:
            - Path=/api/lessons/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
