spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/edu
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8082

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130248@st.hcmuaf.edu.vn
spring.mail.password=lcpo iuxg dyvi prit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=262434113836-v2b2vt0u4m9m1bru5eq99h2uu6ccvqtp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# JWT secret
jwt.secret=TeachAISecretKey2025SuperLongSecretKeyForJWT
jwt.expiration=86400000