CREATE TABLE IF NOT EXISTS action_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NULL,
    username VARCHAR(100) NULL,
    client_identifier VARCHAR(255) NULL,
    action VARCHAR(100) NOT NULL,
    module VARCHAR(80) NOT NULL,
    resource_id VARCHAR(150) NULL,
    http_method VARCHAR(10) NOT NULL,
    endpoint VARCHAR(500) NOT NULL,
    severity VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL,
    description TEXT NULL,
    ip_address VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_action_logs_created_at (created_at),
    INDEX idx_action_logs_user_id (user_id),
    INDEX idx_action_logs_module (module),
    INDEX idx_action_logs_action (action),
    INDEX idx_action_logs_severity (severity),
    INDEX idx_action_logs_status (status),
    CONSTRAINT chk_action_logs_severity CHECK (severity IN ('INFO', 'WARNING', 'DANGER', 'ALERT')),
    CONSTRAINT chk_action_logs_status CHECK (status IN ('SUCCESS', 'FAILED'))
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
