INSERT INTO lesson_contents (subject, grade, name, description, is_active, created_by_user_id, created_at, updated_at) VALUES
  -- Toán lớp 1-5
  ('Toán', '1', 'Làm quen với một số hình', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Các số đến 10', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Phép cộng, phép trừ trong phạm vi 10', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Các số đến 20', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Các số đến 100', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Phép cộng, trừ trong phạm vi 100', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '1', 'Ôn tập cuối năm', 'Nội dung bài học Toán lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Số đến 100', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Cộng, trừ trong phạm vi 100', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Số đến 1000', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Phép nhân, phép chia', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Hình học', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '2', 'Đo lường', 'Nội dung bài học Toán lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Số đến 10 000', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Cộng, trừ, nhân, chia', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Bảng nhân nâng cao', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Phân số (làm quen)', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Hình học', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '3', 'Đo lường', 'Nội dung bài học Toán lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Toán', '4', 'Số lớn', 'Nội dung bài học Toán lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Toán', '4', '4 phép tính', 'Nội dung bài học Toán lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Toán', '4', 'Phân số', 'Nội dung bài học Toán lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Toán', '4', 'Hình học', 'Nội dung bài học Toán lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Toán', '4', 'Đo lường', 'Nội dung bài học Toán lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', 'Số thập phân', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', '4 phép tính với số thập phân', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', 'Phân số nâng cao', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', 'Tỉ số – phần trăm', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', 'Hình học', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Toán', '5', 'Chuyển động', 'Nội dung bài học Toán lớp 5', TRUE, NULL, NOW(), NOW()),

  -- Tiếng Việt lớp 1-5
  ('Tiếng Việt', '1', 'Tiếng Việt - Tiếng mẹ', 'Nội dung bài học Tiếng Việt lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '1', 'Các chữ cái', 'Nội dung bài học Tiếng Việt lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '1', 'Từ vựng cơ bản', 'Nội dung bài học Tiếng Việt lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '1', 'Câu đơn', 'Nội dung bài học Tiếng Việt lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '2', 'Đọc - Hiểu ý chính', 'Nội dung bài học Tiếng Việt lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '2', 'Viết - Tả lại bài', 'Nội dung bài học Tiếng Việt lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '2', 'Nói - Thuyết trình ngắn', 'Nội dung bài học Tiếng Việt lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '3', 'Đọc hiểu truyện ngắn', 'Nội dung bài học Tiếng Việt lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '3', 'Viết - Tả người, vật', 'Nội dung bài học Tiếng Việt lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '3', 'Ngữ pháp cơ bản', 'Nội dung bài học Tiếng Việt lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '4', 'Đọc hiểu văn bản dài', 'Nội dung bài học Tiếng Việt lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '4', 'Viết - Tự sự', 'Nội dung bài học Tiếng Việt lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '4', 'Viết - Thư', 'Nội dung bài học Tiếng Việt lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '5', 'Đọc hiểu - Phân tích tác phẩm', 'Nội dung bài học Tiếng Việt lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '5', 'Viết - Văn học', 'Nội dung bài học Tiếng Việt lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Việt', '5', 'Viết - Báo cáo', 'Nội dung bài học Tiếng Việt lớp 5', TRUE, NULL, NOW(), NOW()),

  -- Tiếng Anh lớp 1-5
  ('Tiếng Anh', '1', 'Bảng chữ cái Anh', 'Nội dung bài học Tiếng Anh lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '1', 'Lời chào cơ bản', 'Nội dung bài học Tiếng Anh lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '1', 'Số từ 1-10', 'Nội dung bài học Tiếng Anh lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '1', 'Màu sắc', 'Nội dung bài học Tiếng Anh lớp 1', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '2', 'Quả vật, động vật', 'Nội dung bài học Tiếng Anh lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '2', 'Thành viên gia đình', 'Nội dung bài học Tiếng Anh lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '2', 'Động từ cơ bản (can, can\'t)', 'Nội dung bài học Tiếng Anh lớp 2', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '3', 'Ngôi nhà - Nôi thất', 'Nội dung bài học Tiếng Anh lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '3', 'Thức ăn - Đồ uống', 'Nội dung bài học Tiếng Anh lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '3', 'Thì hiện tại đơn', 'Nội dung bài học Tiếng Anh lớp 3', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '4', 'Quần áo - Phụ kiện', 'Nội dung bài học Tiếng Anh lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '4', 'Các hoạt động hàng ngày', 'Nội dung bài học Tiếng Anh lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '4', 'Thì quá khứ đơn', 'Nội dung bài học Tiếng Anh lớp 4', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '5', 'Du lịch - Địa điểm', 'Nội dung bài học Tiếng Anh lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '5', 'Truyện tranh - Văn học', 'Nội dung bài học Tiếng Anh lớp 5', TRUE, NULL, NOW(), NOW()),
  ('Tiếng Anh', '5', 'Thì tương lai - Dự định', 'Nội dung bài học Tiếng Anh lớp 5', TRUE, NULL, NOW(), NOW());
